# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "source/docker/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: ".devcontainer/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"
