# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/main/schema/markdownlint-cli2-config-schema.json
#
# dotfiles | markdownlint configuration
#

# Disable some built-in rules
config:
  no-trailing-spaces: false
  no-multiple-blanks: false
  line-length:
    line_length: 120
    heading_line_length: 80
    code_block_line_length: 80
    code_blocks: true
    tables: false
    headings: true
    strict: false
    stern: false

# Include a custom rule package
customRules:
  - markdownlint-rule-titlecase

# Use a plugin to recognize math
markdownItPlugins:
  - ["@iktakahiro/markdown-it-katex"]

# Fix any fixable errors
fix: true

# Define a custom front matter pattern
frontMatter: "<head>[^]*<\/head>"

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to use (only valid at root)
globs:
  - "**/*.md"

# Define glob expressions to ignore
ignores:
  - "ignore*.md"
  - "**/clink-gizmos/README.md"
  - "**/clink-completions/README.md"
  - "**/clink-completions/RELEASENOTES.md"
  - "**/stow/INSTALL.md"
  - "**/secrets/**"

# Additional paths to resolve module locations from
modulePaths:
  - "./modules"

# Disable banner message on stdout (only valid at root)
noBanner: true

# Disable inline config comments
noInlineConfig: false

# Disable progress on stdout (only valid at root)
noProgress: false

# Use a specific formatter (only valid at root)
outputFormatters:
  - - markdownlint-cli2-formatter-default

# Show found files on stdout (only valid at root)
showFound: true
