[tools]
shfmt = "latest"
task = "latest"
shellcheck = "latest"
go = "latest"
actionlint = "latest"
act = "latest"
npm = "10"
node = "22"

# Error: 
#   0: failed to install aqua:skaji/relocatable-perl@5.40.1.0
#   1: unsupported env: windows/amd64
# perl = "latest"
