cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"
tap "neovim/neovim"
tap "koekeishiya/formulae"

brew "cask"
brew "micro"
brew "gpg"
brew "mas"
brew "asdf"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "hub"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "neovim"
brew "ripgrep"
brew "stow"

cask "dropbox"

cask "fsnotes"
cask "hiddenbar"
cask "iterm2"
cask "macpass"
cask "mailmate"
cask "mylio"
cask "skype"
cask "typora"
cask "wire"
