version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: dotfiles
    path: .github/config/cspell-dotfiles.dict
    addWords: true
dictionaries:
  - dotfiles
  - perl
  - en_us
words: []
ignoreWords: []
import: []
