# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: start

  start:
    cmds:
      - cmd: |
          cmd.exe /D /E:ON /C "{{ joinPath .TASKFILE_DIR "setup.bat" }}"
        platforms: [windows]
      - cmd: |
          "{{ joinPath .TASKFILE_DIR "setup.sh" }}"
        platforms: [linux, darwin]

  build:
    vars:
      DOCKERFILE: "{{ .TASKFILE_DIR }}/source/docker/Dockerfile.ubuntu"
      DOCKER_CONTEXT: "{{ .TASKFILE_DIR }}"
    cmds:
      - cmd: >-
          docker build "{{ join .ARGS " "}}"
        vars:
          ARGS: 
            - -f
            - "{{ fromSlash .DOCKERFILE }}"
            - '--pull'
            - '{{if .CLI_FORCE}}--force-rm{{end}}'
            - {{ .CLI_ARGS }}
            - {{ fromSlash .DOCKER_CONTEXT }}

  init:
    cmds:
      - cmd: git submodule update --init --recursive
      - cmd: git fetch --all
      - cmd: proto uninstall --yes yarn
      - cmd: proto uninstall --yes node
      - cmd: proto uninstall --yes npm
      - cmd: proto use
      - cmd: corepack install
      - cmd: corepack enable
        ignore_error: true
      - cmd: yarn install

  lint:
    cmds:
      - cmd: yarn lint

  git-clean:
    vars:
      CLOSE_STDIN: '{{if eq OS "windows"}}<nul{{else}}0<&-{{end}}'
    cmds:
      - cmd: git add .
      - cmd: git clean -xfd {{.CLOSE_STDIN}}
        silent: true
        ignore_error: true

  clean:
    cmds:
      - task: git-clean
      - cmd: git fetch --all
      - cmd: git submodule update --init --recursive
      - task: delete
        vars: { TARGET_DIR: "packages/vim/.vim/bundle/vundle" }
      - task: delete
        vars: { TARGET_DIR: "packages/macos/Library/Application Support/Resources" }
      - task: delete
        vars: { TARGET_DIR: "packages/fish/.config/base16-shell" }
      - task: delete
        vars: { TARGET_DIR: "packages/fish/.config/base16-fzf" }
      - task: delete
        vars: { TARGET_DIR: "packages/fish/.config/git-fuzzy" }
      - task: delete
        vars: { TARGET_DIR: "test/bats" }
      - task: delete
        vars: { TARGET_DIR: "test/test_helper/bats-support" }
      - task: delete
        vars: { TARGET_DIR: "test/test_helper/bats-assert" }

  reset:
    cmds:
      - task: git-clean
      - cmd: git reset --hard origin/main
      - task: git-clean

  test:
    vars:
      LUA_CHECK: "{{ env.HOME }}/scoop/shims/luacheck.exe"
      BUSTED: "{{ env.HOME }}/scoop/shims/busted.exe"
    cmds:
      - cmd: "{{.LUA_CHECK}} ."
        ignore_error: true
      - cmd: "{{.BUSTED}} ."
        ignore_error: true

  delete:  
    vars:
      RUN_WINDOWS: "cmd /D /E:ON /C"
      RUN_UNIX: "sh -c"
      RUN: '{{if eq OS "windows"}}{{.RUN_WINDOWS}}{{ else }}{{.RUN_UNIX}}{{ end }}'
    internal: true
    requires: { vars: [TARGET_DIR] }
    status:
      - 'test -d "{{.TARGET_DIR}}"'
    cmds:
      - cmd: '{{.RUN}} if exist "{{.TARGET_DIR}}" rmdir /s /q "{{.TARGET_DIR}}"'
        platforms: [windows]
      - cmd: '{{.RUN}} rm -rf "{{.TARGET_DIR}}"'
        platforms: [linux, darwin]
