# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  clean:
    cmds:
      - cmd: git fetch --all
      - cmd: git submodule update --init --recursive
      - cmd: git clean -xfd
        silent: true
        ignore_error: true
      - cmd: rmdir /q /s "packages/vim/.vim/bundle/vundle"
      - cmd: rmdir /q /s "packages/macos/Library/Application Support/Resources"
      - cmd: rmdir /q /s "packages/fish/.config/base16-shell"
      - cmd: rmdir /q /s "packages/fish/.config/base16-fzf"
      - cmd: rmdir /q /s "packages/fish/.config/git-fuzzy"
      - cmd: rmdir /q /s "test/bats"
      - cmd: rmdir /q /s "test/test_helper/bats-support"
      - cmd: rmdir /q /s "test/test_helper/bats-assert"
      - cmd: git branch "backups/main"

  reset:
    cmds:
      - cmd: git clean -xfd > nul 2>&1
      - cmd: git reset --hard origin/main
      - cmd: git clean -xfd > nul 2>&1
