# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - cmd: >-
          docker build
          -f "source/docker/Dockerfile.ubuntu"
          --pull
          {{if .CLI_FORCE}}--force-rm{{end}}
          {{ .CLI_ARGS }}
          "{{ .TASKFILE_DIR }}"

  setup:
    cmds:
      - cmd: git submodule update --init --recursive
      - cmd: git fetch --all
      - cmd: proto uninstall --yes yarn
      - cmd: proto uninstall --yes node
      - cmd: proto uninstall --yes npm
      - cmd: proto use
      - cmd: corepack install
      - cmd: corepack enable
        ignore_error: true
      - cmd: yarn install

  lint:
    cmds:
      - cmd: yarn lint

  clean:
    cmds:
      - cmd: git fetch --all
      - cmd: git submodule update --init --recursive
      - cmd: git clean -xfd
        silent: true
        ignore_error: true
      # todo:jve: make this work on non-Windows systems
      - cmd: rmdir /q /s "packages/vim/.vim/bundle/vundle"
      - cmd: rmdir /q /s "packages/macos/Library/Application Support/Resources"
      - cmd: rmdir /q /s "packages/fish/.config/base16-shell"
      - cmd: rmdir /q /s "packages/fish/.config/base16-fzf"
      - cmd: rmdir /q /s "packages/fish/.config/git-fuzzy"
      - cmd: rmdir /q /s "test/bats"
      - cmd: rmdir /q /s "test/test_helper/bats-support"
      - cmd: rmdir /q /s "test/test_helper/bats-assert"
      - cmd: git branch "backups/main"

  reset:
    cmds:
      - cmd: git clean -xfd > nul 2>&1
      - cmd: git reset --hard origin/main
      - cmd: git clean -xfd > nul 2>&1

  test:
    vars:
      LUA_CHECK: "{{ env.HOME }}/scoop/shims/luacheck.exe"
      BUSTED: "{{ env.HOME }}/scoop/shims/busted.exe"
    cmds:
      - cmd: "{{.LUA_CHECK}} ."
        ignore_error: true
      - cmd: "{{.BUSTED}} ."
        ignore_error: true
