#!/usr/bin/perl
#
# This file is part of GNU Stow.
#
# GNU Stow is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GNU Stow is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
#

use strict;
use warnings;

use FindBin qw($RealBin);
use File::Spec;

my @candidates = ();

if ( defined $ENV{STOW_ROOT} && $ENV{STOW_ROOT} ne '' ) {
    push @candidates, File::Spec->catfile( $ENV{STOW_ROOT}, 'configure.ac' );
}

push @candidates,
  File::Spec->catfile( $RealBin, 'configure.ac' ),
  File::Spec->catfile( $RealBin, '..',   'configure.ac' ),
  File::Spec->catfile( 'source', 'stow', 'configure.ac' ),
  File::Spec->catfile( '..',     'configure.ac' ),
  File::Spec->catfile( '.',      'configure.ac' );

my $configure;
for my $candidate (@candidates) {
    if ( -e $candidate ) {
        $configure = $candidate;
        last;
    }
}

my $searched_paths = join( "\n", map { "  - $_" } @candidates );

unless ( defined $configure ) {
    die
"Failed to get Stow version.\nSearch paths:\n$searched_paths\nUnable to find 'configure.ac' file.";
}

open( my $CONF, "<", "$configure" )
  or die
"Failed to get Stow version.\nSearch path: '$configure'\nUnable to find 'configure.ac' file: '$!'";

while ( my $line = <$CONF> ) {
    if ( $line =~ /^AC_INIT\(\[stow\], \[(.+?)\]/ ) {
        print "$1\n";
        exit 0;
    }
}

exit 1;
