name: "stow - nightly"

on:
  # Run at 2 AM UTC every day
  schedule:
    - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker_build:
    name: Docker Perl Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build image
        working-directory: ${{ github.workspace }}/source/stow
        run: |
          bash ./docker/docker-build.sh

      - name: Docker test
        working-directory: ${{ github.workspace }}/source/stow
        run: |
          bash ./docker/docker-test.sh
